// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { z } from "zod";

const databaseUrl = z.url({ error: "DATABASE_URL must be a valid URL" })
  .refine((value) => ["postgres:", "postgresql:"].includes(new URL(value).protocol), {
    message: "DATABASE_URL must be a PostgreSQL URL",
  })
  .parse(process.env["DATABASE_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node-dev --transpile-only prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
